db:
  image: mongo
  expose:
    - "27017"
    - "37017"
web:
  build: .
  expose:
    - "8080"
  env_file:
    - meanbase.env
  links:
      - db:db
nginx:
  restart: always
  build: nginx
  links:
    - web:web
  volumes_from:
    - web
  ports:
    - "80:80"
