db:
  image: mongo
  ports:
    - "27017"
    - "37017"
  command: --smallfiles
web:
  build: .
  dockerfile: Dockerfile.dev
  ports:
    - "3030:3030"
  env_file:
    - meanbase.dev.env
  links:
      - db:db
  volumes:
    - .:/var/www
