db:
  image: mongo
  # volumes:
  #   - './data:/data/db'
  expose:
    - "27017"
    - "37017"
  command: --smallfiles
web:
  build: .
  expose:
    - "80"
  env_file:
    - meanbase.env
  links:
      - db:db
nginx:
  # restart: always
  build: nginx
  links:
    - web:web
  volumes_from:
    - web
  ports:
    - "80:80"
